export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FETCH_DASHBOARD_REQUEST = "FETCH_DASHBOARD_REQUEST";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";

export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_BRAND_FAIL = "FETCH_BRAND_FAIL";

export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";
export const FETCH_STATUS_FAIL = "FETCH_STATUS_FAIL";

export const FETCH_ALL_REPAIR_SUCCESS = "FETCH_ALL_REPAIR_SUCCESS";
export const FETCH_ALL_REPAIR_FAIL = "FETCH_ALL_REPAIR_FAIL";

export const FETCH_REPAIR_PDF_SUCCESS = "FETCH_REPAIR_PDF_SUCCESS";
export const FETCH_REPAIR_PDF_FAIL = "FETCH_REPAIR_PDF_FAIL";

export const REQUEST_REPAIR_SEARCH_SUCCESS = "REQUEST_REPAIR_SEARCH_SUCCESS";
export const REQUEST_REPAIR_SEARCH_FAIL = "REQUEST_REPAIR_SEARCH_FAIL";

export const CREATE_REPAIR_SUCCESS = "CREATE_REPAIR_SUCCESS";
export const CREATE_REPAIR_FAIL = "CREATE_REPAIR_FAIL";

export const UPDATE_REPAIR_SUCCESS = "UPDATE_REPAIR_SUCCESS";
export const UPDATE_REPAIR_FAIL = "UPDATE_REPAIR_FAIL";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const DELETE_REPAIR_SUCCESS = "DELETE_REPAIR_SUCCESS";
export const DELETE_REPAIR_FAIL = "DELETE_REPAIR_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const FETCH_ALL_HISTORY_REPAIR_REQUEST = "FETCH_ALL_HISTORY_REPAIR_REQUEST";
export const FETCH_ALL_HISTORY_REPAIR_SUCCESS = "FETCH_ALL_HISTORY_REPAIR_SUCCESS";
export const FETCH_ALL_HISTORY_REPAIR_FAIL = "FETCH_ALL_HISTORY_REPAIR_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_ALL_USER_SUCCESS = "FETCH_ALL_USER_SUCCESS";
export const FETCH_ALL_USER_FAIL = "FETCH_ALL_USER_FAIL";

export const FETCH_ALL_ROLE_SUCCESS = "FETCH_ALL_ROLE_SUCCESS";
export const FETCH_ALL_ROLE_FAIL = "FETCH_ALL_ROLE_FAIL";

export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL"; 