export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FETCH_BRAND_REQUEST = "FETCH_BRAND_REQUEST";
export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_BRAND_ERROR = "FETCH_BRAND_ERROR";

export const FETCH_STATUS_REQUEST = "FETCH_STATUS_REQUEST";
export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";
export const FETCH_STATUS_ERROR = "FETCH_STATUS_ERROR";

export const FETCH_ALL_REPAIR_REQUEST = "FETCH_ALL_REPAIR_REQUEST";
export const FETCH_ALL_REPAIR_SUCCESS = "FETCH_ALL_REPAIR_SUCCESS";
export const FETCH_ALL_REPAIR_ERROR = "FETCH_ALL_REPAIR_ERROR";

export const FETCH_REPAIR_REQUEST = "FETCH_REPAIR_REQUEST";
export const FETCH_REPAIR_SUCCESS = "FETCH_REPAIR_SUCCESS";
export const FETCH_REPAIR_ERROR = "FETCH_REPAIR_ERROR";

export const CREATE_REPAIR_SUCCESS = "CREATE_REPAIR_SUCCESS";
export const CREATE_REPAIR_FAIL = "CREATE_REPAIR_FAIL";

export const UPDATE_REPAIR_SUCCESS = "UPDATE_REPAIR_SUCCESS";
export const UPDATE_REPAIR_FAIL = "UPDATE_REPAIR_FAIL";

export const FETCH_ALL_HISTORY_REPAIR_REQUEST = "FETCH_ALL_HISTORY_REPAIR_REQUEST";
export const FETCH_ALL_HISTORY_REPAIR_SUCCESS = "FETCH_ALL_HISTORY_REPAIR_SUCCESS";
export const FETCH_ALL_HISTORY_REPAIR_ERROR = "FETCH_ALL_HISTORY_REPAIR_ERROR";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
