export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const FETCH_BRAND_REQUEST = "FETCH_BRAND_REQUEST";
export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_BRAND_FAIL = "FETCH_BRAND_FAIL";

export const FETCH_STATUS_REQUEST = "FETCH_STATUS_REQUEST";
export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";
export const FETCH_STATUS_FAIL = "FETCH_STATUS_FAIL";

export const FETCH_ALL_REPAIR_REQUEST = "FETCH_ALL_REPAIR_REQUEST";
export const FETCH_ALL_REPAIR_SUCCESS = "FETCH_ALL_REPAIR_SUCCESS";
export const FETCH_ALL_REPAIR_FAIL = "FETCH_ALL_REPAIR_FAIL";

export const FETCH_REPAIR_REQUEST = "FETCH_REPAIR_REQUEST";
export const FETCH_REPAIR_SUCCESS = "FETCH_REPAIR_SUCCESS";
export const FETCH_REPAIR_FAIL = "FETCH_REPAIR_FAIL";

export const FETCH_REPAIR_PDF_SUCCESS = "FETCH_REPAIR_PDF_SUCCESS";
export const FETCH_REPAIR_PDF_FAIL = "FETCH_REPAIR_PDF_FAIL";

export const REQUEST_REPAIR_SEARCH_SUCCESS = "REQUEST_REPAIR_SEARCH_SUCCESS";
export const REQUEST_REPAIR_SEARCH_FAIL = "REQUEST_REPAIR_SEARCH_FAIL";

export const CREATE_REPAIR_SUCCESS = "CREATE_REPAIR_SUCCESS";
export const CREATE_REPAIR_FAIL = "CREATE_REPAIR_FAIL";

export const UPDATE_REPAIR_SUCCESS = "UPDATE_REPAIR_SUCCESS";
export const UPDATE_REPAIR_FAIL = "UPDATE_REPAIR_FAIL";

export const DELETE_REPAIR_SUCCESS = "DELETE_REPAIR_SUCCESS";
export const DELETE_REPAIR_FAIL = "DELETE_REPAIR_FAIL";

export const FETCH_ALL_HISTORY_REPAIR_REQUEST = "FETCH_ALL_HISTORY_REPAIR_REQUEST";
export const FETCH_ALL_HISTORY_REPAIR_SUCCESS = "FETCH_ALL_HISTORY_REPAIR_SUCCESS";
export const FETCH_ALL_HISTORY_REPAIR_FAIL = "FETCH_ALL_HISTORY_REPAIR_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
