apiVersion: apps/v1
kind: Deployment
metadata:
    name: trusted-by-ggs
    labels:
        app: trusted-by-ggs
    namespace: prod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: trusted-by-ggs
    template:
        metadata:
            labels:
                app: trusted-by-ggs
        spec:
            volumes:
                - name: tz-config
                  hostPath:
                      path: /usr/share/zoneinfo/Asia/Bangkok
                - name: tz-bk-config
                  configMap:
                      name: tz-bk-config
            containers:
                - name: trusted-by-ggs-fe
                  image: itgadgetstory/trusted-by-ggs:IMAGE_VERSION
                  imagePullPolicy: Always
                  # imagePullSecrets:
                  # - name: gadgetstory-reg
                  volumeMounts:
                      - name: tz-config
                        mountPath: /etc/localtime
                      - name: tz-bk-config
                        mountPath: /etc/timezone
                        subPath: timezone
                  ports:
                      - containerPort: 3000
                  env:
                      - name: REACT_APP_BASE_URL
                        value: "https://trusted-by-ggs-be-prod.gadgetstory.co.th"
---
apiVersion: v1
kind: Service
metadata:
    name: trusted-by-ggs-svc
    namespace: prod
spec:
    selector:
        app: trusted-by-ggs
    #type: NodePort
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          #nodePort: 30081
