name: ci

on:
  release:
    types:
      - created


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ${{ env }}
      - 
        name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4
      -
        name: Get env
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.base_ref_branch }}"
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
          echo "Running on default: ${{ steps.branch-name.outputs.default_branch }}"
          echo "Running on default: ${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "Running on default: ${{ steps.branch-name.outputs.is_default }}"
          echo "Running on default: ${{ steps.branch-name.outputs.is_tag }}"
          echo "Running on default: ${{ steps.branch-name.outputs.ref_branch }}"
          echo "Running on default: ${{ steps.branch-name.outputs.tag }}"
          echo "Running on default: ${{ github.event.release.target_commitish }}"
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: |
      #       itgadgetstory/ggs-repair-system-frontend:latest
      #       itgadgetstory/ggs-repair-system-frontend:${{ env.RELEASE_VERSION }}
