name: ci

on:
  release:
    types:
      - created


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set env for Development
        run: |
          echo "ENVIRONMENT=Development" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.release.target_commitish }}" >> $GITHUB_ENV
          echo "DEPLOY_KEY=${{ secrets.PROEN_KEY }}" >> $GITHUB_ENV
          echo "K8S_HOST=${{ secrets.K8S_HOST }}" >> $GITHUB_ENV
          echo "K8S_USER=${{ secrets.K8S_USER }}" >> $GITHUB_ENV
          echo "K8S_PORT=${{ secrets.K8S_PORT }}" >> $GITHUB_ENV
      - 
        name: Replace env IF Production
        if: github.event.release.target_commitish == 'main'
        run: |
          echo "ENVIRONMENT=Production" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.release.target_commitish }}" >> $GITHUB_ENV
          echo "DEPLOY_KEY=${{ secrets.PROEN_KEY }}" >> $GITHUB_ENV
          echo "K8S_HOST=${{ secrets.K8S_HOST }}" >> $GITHUB_ENV
          echo "K8S_USER=${{ secrets.K8S_USER }}" >> $GITHUB_ENV
          echo "K8S_PORT=${{ secrets.K8S_PORT }}" >> $GITHUB_ENV
      -
        name: Show ENV
        run: |
          echo ${{ env.ENVIRONMENT}}
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ env.BRANCH_NAME }}
          echo ${{ env.DEPLOY_KEY}}
          echo ${{ env.K8S_HOST }}
          echo ${{ env.K8S_USER }}
          echo ${{ env.K8S_PORT }}
      - 
        name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.K8S_HOST }}
          username: ${{ env.K8S_USER }}
          key: ${{ env.DEPLOY_KEY}}
          port: ${{ env.K8S_PORT }}
          script: |
            whoami
            pwd
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: |
      #       itgadgetstory/ggs-repair-system-frontend:latest
      #       itgadgetstory/ggs-repair-system-frontend:${{ env.RELEASE_VERSION }}
